### ISSUE TITLE
about yml

### ISSUE THREAD

**Issue by qzhou711** [jokla/aruco_gridboard#1]
Hi jokla,
Thanks for your work.
I just wonder how to generate the yml and yaml file about the boards.
Thanks again!
Qiang

**Comment by jokla** [comment]
Hi @bamboosdu, You can follow this guide (see Grid Board): https://docs.opencv.org/3.1.0/db/da9/tutorial_aruco_board_detection.html

Cheers

**Comment by prasgane** [comment]
Hi Jokla,
I too am curious how you got layout.yaml. I looked at the link and it doesn't say anything about the layout configuration. Could you please shed some more light on this.

**Comment by jokla** [comment]
Hi @prasgane , It was given to me, I didn't create it. This tutorial (https://github.com/clearpathrobotics/aruco) in mentioning something about the yml file. Let me know if that helps!

**Comment by prasgane** [comment]
Hello @jokla, 

I have actually taken a look at that but I cant generate aruco markers from the same dictionary as we have been using at our lab. Additionally the yaml file format is different from what you use in your code.

Is there any chance you have the image of the aruco board? So I could print that out and test your code?

**Comment by jokla** [comment]
Found it! You can download it here:
https://github.com/jokla/aruco_gridboard/blob/master/data/sans-titre.png

Hope this helps!

**Comment by prasgane** [comment]
Thank you! This helps a lot.
